export interface PromptShowcaseItem {
	id: string;
	phase: string;
	title: string;
	context: string;
	prompt: string;
	tags: string[];
}

// Edit this array to add your real prompts. The page layout updates automatically.
export const promptShowcase: PromptShowcaseItem[] = [
	{
		id: '01',
		phase: 'Discovery',
		title: 'Defining the product and constraints',
		context:
			'Describe the problem you wanted AI to help frame and the constraints you established.',
		prompt:
			'I want to create a simple personalized learning platform called CodeCraftHub where developers can track courses they want to learn. Requirements: - Use Node.js with Express framework - Store course data in a simple JSON text file (NO database needed) - No authentication or user management needed - Focus on learning REST API basics Each course should track: - Course name - Description - Target completion date - Current status (Not Started, In Progress, Completed) Recommend: 1. A simple project structure for beginners 2. The REST API endpoints to be created 3. How to store and retrieve data from a JSON file',
		tags: ['Product thinking', 'Requirements', 'Scope'],
	},
	{
		id: '02',
		phase: 'Architecture',
		title: 'Designing the full-stack structure',
		context:
			'Show how you asked AI to connect the frontend, API, and JSON-based storage.',
		prompt:
			'Now create the complete Node.js Express code for app.js with these requirements: 1. Create an Express REST API with all CRUD operations for courses 2. Store data in a JSON file called "courses.json" 3. Include these endpoints: - POST /api/courses - Add a new course - GET /api/courses - Get all courses - GET /api/courses/ - Get a specific course - PUT /api/courses/ - Update a course - DELETE /api/courses/ - Delete a course 4. Each course must have: - id (auto-generated, starting from 1) - name (required) - description (required) - target_date (required, format YYYY-MM-DD) - status (required, must be: "Not Started", "In Progress", or "Completed") - created_at (auto-generated timestamp) 5. Include proper error handling for: - Missing required fields - Course not found - Invalid status values - File read/write errors 6. Add helpful comments throughout the code for beginners 7. Make sure the app creates courses.json automatically if it doesn\'t exist 8. The server should run on port 5000',
		tags: ['Express', 'REST API', 'System design'],
	},
	{
		id: '03',
		phase: 'UI generation',
		title: 'Creating the first dashboard with Bolt',
		context:
			'Capture the visual direction, interaction requirements, and constraints given to Bolt.new.',
		prompt: `Create a learning management dashboard with API operations.

Requirements:

1. Single HTML file with embedded CSS and JavaScript
2. Display all courses in a table/card layout
3. Include a form to add new courses
4. Allow editing courses inline or in a modal
5. Include delete buttons for each course
6. Use vanilla JavaScript (no frameworks like React)
7. Use basic CSS for styling (no frameworks like Bootstrap)
8. Generate only one HTML file with all JS and CSS
9. Focus on calling backend APIs
10. Do not use any database

Technical details:

- Base API URL: [YOUR_BACKEND_URL]/api/courses
- All API calls should handle loading states and errors

API endpoints to implement:

1. GET /api/courses - fetch all courses
2. POST /api/courses - create new course (body: name, description, target_date, status)
3. PUT /api/courses/{id} - update course (body: any fields to update)
4. DELETE /api/courses/{id} - delete course

Course fields:

- id (read-only, auto-generated by backend)
- name (required, text input)
- description (required, textarea)
- target_date (required, date input in YYYY-MM-DD format)
- status (required, dropdown with: "Not Started", "In Progress", "Completed")
- created_at (read-only, displayed as formatted date)

Design:

- Title/Header with "CodeCraftHub: Your Learning Management Platform"
- Add Course form at the top with all fields
- Course list below showing all courses
- Each course should have Edit and Remove buttons
- Use a simple, clean table or card layout
- Show loading spinner while fetching/saving data
- Show success/error messages for all operations
- Make it responsive for mobile devices

Colors:

- Use a professional purple/amber theme:
  - #8B5CF6 for primary
  - #F59E0B for success
  - #EF4444 for delete

Error handling:

- Show error if API calls fail
- Validate all required fields before submission
- Show user-friendly error messages`,
		tags: ['Bolt.new', 'UI design', 'Vibe coding'],
	},
	{
		id: '04',
		phase: 'Verification',
		title: 'Testing the complete user flow',
		context:
			'Share how you prompted AI to test beyond compilation and cover real user behavior.',
		prompt:
			'Create a package.json file for this Node.js project with: - Project name: codecrafthub - Version: 1.0.0 - Description: Personal learning goal tracker API - Dependencies: express - Start script to run app.js. Additionally, Create a README.md file that includes: - Project overview - Features - Installation instructions - How to run the application - API endpoint documentation with examples - Troubleshooting section. Finally,Test and verify that: 1. All endpoints return appropriate responses 2. Data persists in courses.json 3.Error handling works correctly',
		tags: ['Vitest', 'Integration tests', 'Quality'],
	},
	{
		id: '05',
		phase: 'Deployment',
		title: 'Shipping and debugging on Vercel',
		context:
			'Document the prompt sequence used to deploy, inspect failures, and correct routing.',
		prompt:
			'Deploy the app to Vercel. Ensure that: 1. The app runs correctly on Vercel 2. All API endpoints are accessible 3. The courses.json file is created and updated properly 4. Any deployment errors are resolved',
		tags: ['Vercel', 'Debugging', 'Production'],
	},
];
